NguoiDung/urls.py
from django.urls import path
from . import views

app_name = 'NguoiDung'
urlpatterns = [
    path('login/', views.LoginClass.as_view(), name='login'),
    path('register/', views.RegisterClass.as_view(), name='register'),
<<<<<<< HEAD
    path('profile/<id>', views.detail_view, name='profile'),
    path('update/<id>', views.update_view, name='update'),
=======
    path('profile/', views.ProfileClass.as_view(), name='profile'),
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729
]

PhongTro/urls.py
from django.urls import path
from . import views

app_name = 'PhongTro'
urlpatterns = [
    path('', views.index, name='index'),
<<<<<<< HEAD
    path('add', views.post, name='add'),
    path('gets/', views.getAll.as_view(), name='getall'),
    path('detail/<int:PhongTro_id>', views.getdetail.as_view(), name='detail'),
    path('edit/<int:pk>', views.PhongTroUpdate.as_view(), name='phongtro_edit'),
    path('delete/<int:pk>', views.PhongTroDelete.as_view(), name='phongtro_delete'),
=======
    path('add/', views.save_news_class.as_view(), name='add'),
    path('gets/', views.getAll.as_view(), name='getall'),
    path('detail/<int:PhongTro_id>', views.getdetail.as_view(), name='detail'),
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

    path('ajax/load-huyen/', views.load_huyen, name='ajax_load_districts'),
    path('ajax/load-xa/', views.load_xa, name='ajax_load_wards'),
    path('ajax/load-duong/', views.load_duong, name='ajax_load_streets')
]

TimPhongTro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PhongTro/', include("PhongTro.urls")),
    path('NguoiDung/',include("NguoiDung.urls")),
    path('', include("core.urls"))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.Home.as_view(), name='index'),
    path('/about', views.About.as_view(), name='about'),
    path('/contact', views.Contact.as_view(), name='contact'),
    path('/huongdan', views.HuongDan.as_view(), name='huongdan')
]

NguoiDung/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
from django.utils import timezone


class NguoiDung(AbstractUser):
    DiaChi = models.CharField(max_length=100, default='')
    GENDER_MALE = 0
    GENDER_FEMALE = 1
    GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE, 'Female')]
    GioiTinh = models.IntegerField(choices=GENDER_CHOICES, default=GENDER_MALE)
    NgaySinh = models.DateField(blank=True, null=True, default=None)

    def __str__(self):
        return self.username

NguoiDung/forms.py
from django import forms
from .models import NguoiDung
from django.contrib.auth.forms import UserCreationForm

from DichVu.models import DichVu
from TinhTP.models import TinhTP

from HuyenQuan.models import HuyenQuan

from NguoiDung.models import NguoiDung

<<<<<<< HEAD

class NguoiDungForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = NguoiDung
        fields = ('username', 'email', 'DiaChi', 'GioiTinh', 'NgaySinh')
=======
class NguoiDungForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = NguoiDung
        fields = ('username','email','DiaChi', 'GioiTinh', 'NgaySinh')



>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

NguoiDung/views.py
<<<<<<< HEAD
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
=======
from django.http import HttpResponse
from django.shortcuts import render, redirect
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729
from django.contrib.auth import authenticate, login

# Create your views here.
from django.views import View
<<<<<<< HEAD
from django.views.generic import UpdateView

from .models import NguoiDung
from .forms import NguoiDungForm
from .models import NguoiDung
=======

from .models import NguoiDung
from .forms import NguoiDungForm
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729
from PhongTro.models import PhongTro


class LoginClass(View):
    def get(self, request):
        return render(request, 'NguoiDung/login.html')

    def post(self, request):
        tk = request.POST.get('username')
        mk = request.POST.get('password')
        my_user = authenticate(username=tk, password=mk)
        if my_user is None:
            return HttpResponse('User không tồn tại, Đăng nhập thất bại')
        login(request, my_user)
        return redirect('/', {'username': tk})


class RegisterClass(View):
    def get(self, request):
        a = NguoiDungForm()
        return render(request, 'NguoiDung/register.html', {'f': a})

    def post(self, request):
        nd = NguoiDungForm(request.POST)
        if nd.is_valid():
            nd.save()
            return redirect('/NguoiDung/login')
        else:
            return HttpResponse('Dwx liệu không validate')


class ProfileClass(View):
    def get(self, request, **kwargs):
        a = self.request.GET.get('id')
        user_id = self.request.user
<<<<<<< HEAD
        dsach_tin_dang = PhongTro.objects.filter(NguoiDung_id=user_id)
        return render(request, 'NguoiDung/profile.html', {'dsach_tin_dang': dsach_tin_dang})


def detail_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # add the dictionary during initialization
    context["data"] = NguoiDung.objects.get(id=id)
    context["dsach_tin_dang"] = PhongTro.objects.filter(NguoiDung_id=id)
    return render(request, "NguoiDung/profile.html", context)


# update view for details
def update_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # fetch the object related to passed id
    obj = get_object_or_404(NguoiDung, id=id)

    # pass the object as instance in form
    form = NguoiDung(request.POST or None, instance=obj)

    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/" + id)

        # add form dictionary to context
    context["form"] = form

    return render(request, "NguoiDung/update.html", context)
=======
        print(a)
        print(self)
        dsach_tin_dang = PhongTro.objects.filter(NguoiDung_id=user_id)
        return render(request, 'NguoiDung/profile.html', {'dsach_tin_dang': dsach_tin_dang})
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

templates/NguoiDung/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Aler Template">
    <meta name="keywords" content="Aler, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    {% block cssblock %}

    {% endblock %}
</head>

<body>
    <!-- Navbar Section Begin -->
    {% include 'homepage/navbar.html' %}
    <!-- Navbar Section End -->

    {% block content %}

    {% endblock %}
    <!-- Logo Carousel End -->

    <!-- Contact Section Begin -->

    <!-- Contact Section End -->

    <!-- Footer Section Begin -->
    {% include 'homepage/footer.html' %}
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    {% block jsblock %}

    {% endblock %}
</body>

</html>

templates/NguoiDung/index.html
{% extends 'NguoiDung/base.html' %}
{% load static %}

    {% block cssblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    {% endblock %}

    {% block content %}
        <form method="POST">
            <div align="center" style="background-color: gray;">
                <div magintop>
                    {% csrf_token %}
                    {% for key, value in form.errors.items %}
                        {{value}}
                    {% endfor %}
                    <p><label>Tài khoản:</label><input type="text" name="username"></p>
                    <p><label>Mật khẩu:</label><input type="password" name="password"></p>
                    <input type="hidden" name="next" value="/"/>
                    <input type="submit" value="Đăng nhập"/>
                    <a href="{% url 'NguoiDung:register' %}">Đăng ký</a>
                </div>
            </div>
        </form>
    {% endblock %}

    {% block jsblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.richtext.min.js' %}"></script>
    <script src="{% static 'js/image-uploader.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% endblock %}

templates/NguoiDung/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'NguoiDung/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'NguoiDung/css/style.css' %}">
</head>
<body>

    <div class="main">

        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="{% static 'NguoiDung/images/signin-image.jpg' %}" alt="sing up image"></figure>
                        <a href="{% url 'NguoiDung:register' %}" class="signup-image-link">Create an account</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="username" id="your_name" placeholder="Your Name"/>
                            </div>
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="password" id="your_pass" placeholder="Password"/>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                            </div>
                        </form>
                        <div class="social-login">
                            <span class="social-label">Or login with</span>
                            <ul class="socials">
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'NguoiDung/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'NguoiDung/js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/NguoiDung/profile.html
{% extends 'homepage/base.html' %}
{% load static %}

<<<<<<< HEAD
{% block cssblock %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/elegant-icons.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/nice-select.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/slicknav.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="container">
    <h2 style="text-align: center;">Thông tin cá nhân</h2>
    <br>
    <div style="display: inline-block;">
        <label for="" style="">Tên đăng nhập: </label>
        <input disabled style="width: 700px; text-align: center; margin-left: 100px;" type="text"
               value="{{ user.username }}">
    </div>
    <br><br>
    <div style="display: inline-block;">
        <label for="" style="">Email: </label>
        <input style="width: 700px; text-align: center; margin-left: 172px;" type="text" value="{{ user.email }}">
    </div>
    <br><br>
    <div style="display: inline-block;">
        <label for="">Địa chỉ: </label>
        <input style="width: 700px; text-align: center; margin-left: 165px;" type="text" value="{{ user.DiaChi }}">
    </div>
    <br><br>
    <div style="display: inline-block;">
        <label for="">Ngày Sinh: </label>
        <input style="width: 700px; text-align: center; margin-left: 135px;" type="text" value="{{ user.NgaySinh }}">
    </div>
    <br><br>
    <div style="display: inline-block;">
        <label for="">Giới tính: </label>
        <input style="width: 700px; text-align: center; margin-left: 150px;" type="text" value="{{ user.GioiTinh }}">
    </div>
    <br><br>
    <a href="{% url 'NguoiDung:update' user.id %}"><input style="background-color: green;" type="button">Sửa đổi</input>
    </a>
</div>
<div class="container">
    <h2>TIN ĐÃ ĐĂNG</h2>
    {% for item in dsach_tin_dang %}
    <div class="container mt-2 mb-5">
        <div class="row">
            <div class="w-100  col-11">
                <div class="media">
                    <img alt="Generic placeholder image" class="ml-3" src="{{ item.Anh.url }}"
                         style="width: 150px; height: 106px;">
                    <div class="media-body ml-1 w-100 border" style="height: 106px">
                        <strong><a class="mt-0 mb-1 ml-2" href="{% url 'PhongTro:detail' item.id%}">{{ item.TieuDe }}</a></strong>
                        <br>
                        <strong class="mt-0 mb-1 ml-2" style="color: #37a344;"> Dịch vụ: {{ item.DichVu }}</strong>
                        <h6 class="mt-0 mb-1 ml-2">Địa chỉ: {{ item.street }},{{ item.ward }},{{ item.district }},{{ item.province }}</h6>
                        <strong class="mt-0 mb-1 ml-2">{{ item.Gia }} vnd/tháng</strong>
                    </div>
                </div>
            </div>
            <div class="col-1 mt-4">
                <a href="{% url 'PhongTro:phongtro_edit' item.id %}">
                    <svg class="bi bi-pencil-square" fill="currentColor" height="1em" viewBox="0 0 16 16"
                         width="1em"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"
                              fill-rule="evenodd"/>
                    </svg>
                </a>
                <br>
                <a href="{% url 'PhongTro:phongtro_delete' item.id %}">
                    <svg class="bi bi-trash" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
                              fill-rule="evenodd"/>
                    </svg>
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

{% block jsblock %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.richtext.min.js' %}"></script>
<script src="{% static 'js/image-uploader.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}
=======
    {% block cssblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    {% endblock %}

    {% block content %}
        <div class="container" >
            <h2 style="text-align: center;" >Cập nhật thông tin cá nhân</h2>
            <br>
            <div style="display: inline-block;">
                <label for="" style="">Tên đăng nhập: </label>
                <input type="text" style="width: 700px; text-align: center; margin-left: 100px;" value="{{ user.username }}" disabled>
            </div>
            <br><br>
            <div style="display: inline-block;">
                <label for="" style="">Email: </label>
                <input type="text" style="width: 700px; text-align: center; margin-left: 172px;" value="{{ user.email }}">
            </div>
            <br><br>
            <div style="display: inline-block;">
                <label for="">Địa chỉ: </label>
                <input type="text" style="width: 700px; text-align: center; margin-left: 165px;" value="{{ user.DiaChi }}">
            </div>
            <br><br>
            <div style="display: inline-block;">
                <label for="">Ngày Sinh: </label>
                <input type="text" style="width: 700px; text-align: center; margin-left: 135px;" value="{{ user.NgaySinh }}">
            </div>
            <br><br>
            <div style="display: inline-block;">
                <label for="">Giới tính: </label>
                <input type="text" style="width: 700px; text-align: center; margin-left: 150px;" value="{{ user.GioiTinh }}">
            </div>
            <br><br>
            <button style="background-color: green; color: #ffffff; margin-bottom:100px; margin-left: 830px; width: 100px; height: 40px;">Lưu</button>
        </div>
        <div class="container">
            <h2>TIN ĐÃ ĐĂNG</h2>
                {% for item in dsach_tin_dang %}
                    <div class="container">
                      <div class="row">
                          <div class="">
                              <a href="/PhongTro/detail/{{item.id}}"><h3>{{ item.TieuDe }}</h3></a>
                              <img src="{{ item.Anh.url }}" alt="{{ item.Anh.url }}" style="width:150px;height:100px;">

                          </div>
                      </div>
                    </div>
                {% endfor %}
        </div>
        {{ user.id }}

    {% endblock %}

    {% block jsblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.richtext.min.js' %}"></script>
    <script src="{% static 'js/image-uploader.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% endblock %}
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

templates/NguoiDung/register.html
<!--{% load static %}-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

     <!--Font Icon-->
    <link rel="stylesheet" href="{% static 'NguoiDung/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'NguoiDung/css/style.css' %}">
</head>
<body>


    <div class="main">

         <!--Sign up form-->
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="register-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name"><i class="zmdi zmdi-account material-icons-name"> Tài khoản</i></label>
                                <br><br>
                                {{ f.username }}
                            </div>
                            <div class="form-group">
                                <label for="email"><i class="zmdi zmdi-email"> Email</i></label>
                                <br><br>
                                {{ f.email }}
                            </div>
                            <div class="form-group">
                                <label for="pass"><i class="zmdi zmdi-lock"> Mật khẩu</i></label>
                                <br><br>
                                {{ f.password1 }}
                            </div>
                            <div class="form-group">
                                <label for="re-pass"><i class="zmdi zmdi-lock-outline"> Nhập lại mật khẩu</i></label>
                                <br><br>
                                {{ f.password2 }}
                            </div>
                            <div class="form-group">
                                <label for=""><i class="zmdi zmdi-lock-outline"> Giới tính</i></label>
                                <br><br>
                                {{ f.GioiTinh }}
                            </div>
                            <div class="form-group">
                                <label for=""><i class="zmdi zmdi-lock-outline"> Ngày sinh</i></label>
                                <br><br>
                                {{ f.NgaySinh }}
                            </div>
                            <div class="form-group">
                                <label for=""><i class="zmdi zmdi-lock-outline"> Địa chỉ</i></label>
                                <br><br>
                                {{ f.DiaChi }}
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                                <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'NguoiDung/images/signup-image.jpg' %}" alt="sing up image"></figure>
                        <a href="{% url 'NguoiDung:login' %}" class="signup-image-link">I am already member</a>
                    </div>
                </div>
            </div>
        </section>


<!--
        <form method="post">
            {% csrf_token %}
&lt;!&ndash;            {% for key, value in form.errors.items %}
                {{value}}
            {% endfor %}&ndash;&gt;
            {{ f }}
            <input type="submit" value="dk">
        </form>
-->

    </div>

    <!-- JS -->
    <script src="{% static 'NguoiDung/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'NguoiDung/js/main.js' %}"></script>
</body> <!--This templates was made by Colorlib (https://colorlib.com) -->
</html>