NguoiDung/urls.py
from django.urls import path
from . import views

app_name = 'NguoiDung'
urlpatterns = [
    path('login/', views.LoginClass.as_view(), name='login'),
    path('register/', views.RegisterClass.as_view(), name='register'),
<<<<<<< HEAD
    path('profile/<id>', views.detail_view, name='profile'),
    path('update/<id>', views.update_view, name='update'),
=======
    path('profile/', views.ProfileClass.as_view(), name='profile'),
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729
]

PhongTro/urls.py
from django.urls import path
from . import views

app_name = 'PhongTro'
urlpatterns = [
    path('', views.index, name='index'),
<<<<<<< HEAD
    path('add', views.post, name='add'),
    path('gets/', views.getAll.as_view(), name='getall'),
    path('detail/<int:PhongTro_id>', views.getdetail.as_view(), name='detail'),
    path('edit/<int:pk>', views.PhongTroUpdate.as_view(), name='phongtro_edit'),
    path('delete/<int:pk>', views.PhongTroDelete.as_view(), name='phongtro_delete'),
=======
    path('add/', views.save_news_class.as_view(), name='add'),
    path('gets/', views.getAll.as_view(), name='getall'),
    path('detail/<int:PhongTro_id>', views.getdetail.as_view(), name='detail'),
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

    path('ajax/load-huyen/', views.load_huyen, name='ajax_load_districts'),
    path('ajax/load-xa/', views.load_xa, name='ajax_load_wards'),
    path('ajax/load-duong/', views.load_duong, name='ajax_load_streets')
]

TimPhongTro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PhongTro/', include("PhongTro.urls")),
    path('NguoiDung/',include("NguoiDung.urls")),
    path('', include("core.urls"))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.Home.as_view(), name='index'),
    path('/about', views.About.as_view(), name='about'),
    path('/contact', views.Contact.as_view(), name='contact'),
    path('/huongdan', views.HuongDan.as_view(), name='huongdan')
]

templates/homepage/CategoriesSection.html
{% load static %}
    <section class="categories-section">
        <div class="cs-item-list">
            <div class="cs-item set-bg" data-setbg="{% static 'img/categories/cat-1.jpg' %}">
                <div class="cs-text">
                    <h5>Nhà trọ</h5>
                    <span>5000 căn</span>
                </div>
            </div>
            <div class="cs-item set-bg" data-setbg="{% static 'img/categories/cat-2.jpg' %}">
                <div class="cs-text">
                    <h5>Nhà nghỉ</h5>
                    <span>1000 phòng</span>
                </div>
            </div>
            <div class="cs-item set-bg" data-setbg="{% static 'img/categories/cat-3.jpg' %}">
                <div class="cs-text">
                    <h5>Căn hộ</h5>
                    <span>1000 căn</span>
                </div>
            </div>
            <div class="cs-item set-bg" data-setbg="{% static 'img/categories/cat-4.jpg' %}">
                <div class="cs-text">
                    <h5>Mặt bằng</h5>
                    <span>500 tin</span>
                </div>
            </div>
            <div class="cs-item set-bg" data-setbg="{% static 'img/categories/cat-5.jpg' %}">
                <div class="cs-text">
                    <h5>Ở ghép</h5>
                    <span>400 tin</span>
                </div>
            </div>
        </div>
    </section>

templates/homepage/ChooseusSectionBegin.html
{% load static %}
<section class="chooseus-section spad set-bg" data-setbg="{% static 'img/chooseus/chooseus-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="chooseus-text">
                        <div class="section-title">
                            <h4>Tại sao chọn aler.com?</h4>
                        </div>
                        <p>Chúng tôi biết bạn có rất nhiều lựa chọn, nhưng Aler.com tự hào là trang web đứng top google về các từ khóa: <b style="color: #5dbcd2">cho thuê phòng trọ, nhà trọ, thuê nhà nguyên căn, cho thuê căn hộ, tìm người ở ghép...</b>Vì vậy tin của bạn đăng trên website sẽ tiếp cận được với nhiều khách hàng hơn, do đó giao dịch nhanh hơn, tiết kiệm chi phí hơn</p>
                    </div>
                    <div class="chooseus-features">
                        <div class="cf-item">
                            <div class="cf-pic">
                                <img src="{% static 'img/chooseus/chooseus-icon-1.png' %}" alt="">
                            </div>
                            <div class="cf-text">
                                <h5>70.000+</h5>
                                <p>Thành viên</p>
                            </div>
                        </div>
                        <div class="cf-item">
                            <div class="cf-pic">
                                <img src="{% static 'img/chooseus/chooseus-icon-2.png' %}" alt="">
                            </div>
                            <div class="cf-text">
                                <h5>100.000+</h5>
                                <p>Tin đăng</p>
                            </div>
                        </div>
                        <div class="cf-item">
                            <div class="cf-pic">
                                <img src="{% static 'img/chooseus/chooseus-icon-3.png' %}" alt="">
                            </div>
                            <div class="cf-text">
                                <h5>300.000+</h5>
                                <p>Lượt truy cập/tháng</p>
                            </div>
                        </div>
                        <div class="cf-item">
                            <div class="cf-pic">
                                <img src="{% static 'img/chooseus/chooseus-icon-4.png' %}" alt="">
                            </div>
                            <div class="cf-text">
                                <h5>2.500.000+</h5>
                                <p>Lượt xem/tháng</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

templates/homepage/FeaturePropertySection.html
{% load static %}
    <section class="feature-property-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 p-0">
                    <div class="feature-property-left">
                        <div class="section-title">
                            <h4>Feature PROPERTY</h4>
                        </div>
                        <ul>
                            <li>Apartment</li>
                            <li>House</li>
                            <li>Office</li>
                            <li>Hotel</li>
                            <li>Villa</li>
                            <li>Restaurent</li>
                        </ul>
                        <a href="#">View all property</a>
                    </div>
                </div>
                <div class="col-lg-8 p-0">
                    <div class="fp-slider owl-carousel">
                        <div class="fp-item set-bg" data-setbg="{% static 'img/feature-property/fp-1.jpg' %}">
                            <div class="fp-text">
                                <h5 class="title">Home in Merrick Way</h5>
                                <p><span class="icon_pin_alt"></span> 3 Middle Winchendon Rd, Rindge, NH 03461</p>
                                <div class="label">For Rent</div>
                                <h5>$ 289.0<span>/month</span></h5>
                                <ul>
                                    <li><i class="fa fa-object-group"></i> 2, 283</li>
                                    <li><i class="fa fa-bathtub"></i> 03</li>
                                    <li><i class="fa fa-bed"></i> 05</li>
                                    <li><i class="fa fa-automobile"></i> 01</li>
                                </ul>
                            </div>
                        </div>
                        <div class="fp-item set-bg" data-setbg="{% static 'img/feature-property/fp-2.jpg' %}">
                            <div class="fp-text">
                                <h5 class="title">Home in Merrick Way</h5>
                                <p><span class="icon_pin_alt"></span> 3 Middle Winchendon Rd, Rindge, NH 03461</p>
                                <div class="label">For Rent</div>
                                <h5>$ 289.0<span>/month</span></h5>
                                <ul>
                                    <li><i class="fa fa-object-group"></i> 2, 283</li>
                                    <li><i class="fa fa-bathtub"></i> 03</li>
                                    <li><i class="fa fa-bed"></i> 05</li>
                                    <li><i class="fa fa-automobile"></i> 01</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

templates/homepage/TeamSection.html
{% load static %}
    <section class="team-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    <div class="section-title">
                        <h4>Latest Property</h4>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="team-btn">
                        <a href="#"><i class="fa fa-user"></i> ALL counselor</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="ts-item">
                        <div class="ts-text">
                            <img src="{% static 'img/team/team-1.jpg' %}" alt="">
                            <h5>Ashton Kutcher</h5>
                            <span>123-455-688</span>
                            <p>Ipsum dolor amet, consectetur adipiscing elit, eiusmod tempor incididunt lorem.</p>
                            <div class="ts-social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-envelope-o"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="ts-item">
                        <div class="ts-text">
                            <img src="{% static 'img/team/team-2.jpg' %}" alt="">
                            <h5>Ashton Kutcher</h5>
                            <span>123-455-688</span>
                            <p>Ipsum dolor amet, consectetur adipiscing elit, eiusmod tempor incididunt lorem.</p>
                            <div class="ts-social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-envelope-o"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="ts-item">
                        <div class="ts-text">
                            <img src="{% static 'img/team/team-3.jpg' %}" alt="">
                            <h5>Ashton Kutcher</h5>
                            <span>123-455-688</span>
                            <p>Ipsum dolor amet, consectetur adipiscing elit, eiusmod tempor incididunt lorem.</p>
                            <div class="ts-social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-envelope-o"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

templates/homepage/TestimonialSection.html
{% load static %}
    <section class="testimonial-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h4>Khách hàng nói gì về chúng tôi?</h4>
                    </div>
                </div>
            </div>
            <div class="row testimonial-slider owl-carousel">
                <div class="col-lg-6">
                    <div class="testimonial-item">
                        <div class="ti-text">
                            <p>Trước khi biết website Aler, mình phải tốn nhiều công sức và chi phí cho việc đăng tin cho thuê:
                                từ việc phát tờ rơi, dán giấy, và đăng lên các website khác nhưng hiệu quả không cao. Từ khi biết website aler.com,
                                mình đã thử đăng tin lên
                                và đánh giá hiệu quả khá cao trong khi chi phí khá thấp, không còn tình trạng phòng trống kéo dài.</p>
                        </div>
                        <div class="ti-author">
                            <div class="ta-pic">
                                <img src="{% static 'img/testimonial-author/tam.jpg' %}" alt="">
                            </div>
                            <div class="ta-text">
                                <h5>Trần Thanh Tâm</h5>
                                <span>Trứng rán cần mỡ, bắp cần bơ</span>
                                <div class="ta-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="testimonial-item">
                        <div class="ti-text">
                            <p>Trước khi biết website Aler, mình phải tốn nhiều công sức và chi phí cho việc đăng tin cho thuê:
                                từ việc phát tờ rơi, dán giấy, và đăng lên các website khác nhưng hiệu quả không cao.
                                Từ khi biết website aler.com, mình đã thử đăng tin lên và đánh giá hiệu quả khá cao trong khi chi phí khá thấp, không còn tình trạng phòng trống kéo dài.</p>
                        </div>
                        <div class="ti-author">
                            <div class="ta-pic">
                                <img src="{% static 'img/testimonial-author/huanrose.jpg' %}" alt="">
                            </div>
                            <div class="ta-text">
                                <h5>Huấn Rose</h5>
                                <span>Không làm thì chỉ có ăn ...</span>
                                <div class="ta-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="testimonial-item">
                        <div class="ti-text">
                            <p>Trước khi biết website Aler, mình phải tốn nhiều công sức và chi phí cho việc đăng tin cho thuê:
                                từ việc phát tờ rơi, dán giấy, và đăng lên các website khác nhưng hiệu quả không cao.
                                Từ khi biết website aler.com, mình đã thử đăng tin lên và đánh giá hiệu quả khá cao trong khi chi phí khá thấp, không còn tình trạng phòng trống kéo dài.</p>
                        </div>
                        <div class="ti-author">
                            <div class="ta-pic">
                                <img src="{% static 'img/testimonial-author/dnt.jpg' %}" alt="">
                            </div>
                            <div class="ta-text">
                                <h5>Đỗ Nam Trung</h5>
                                <span>Diễn viên</span>
                                <div class="ta-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

templates/homepage/base.html
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Aler Template">
    <meta name="keywords" content="Aler, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    {% block cssblock %}

    {% endblock %}
</head>

<body>
    <!-- Navbar Section Begin -->
    {% include 'homepage/navbar.html' %}
    <!-- Navbar Section End -->

    {% block content %}

    {% endblock %}
    <!-- Logo Carousel End -->

    <!-- Contact Section Begin -->

    <!-- Contact Section End -->

    <!-- Footer Section Begin -->
    {% include 'homepage/footer.html' %}
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    {% block jsblock %}

    {% endblock %}
</body>

</html>

templates/homepage/contact.html
{% extends 'homepage/base.html' %}
{% load static %}
    {% block cssblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    {% endblock %}

    {% block content %}
<!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Wrapper Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="canvas-close">
            <span class="icon_close"></span>
        </div>
        <div class="logo">
            <a href="{% static './index.html' %}">
                <img src="{% static 'img/logo.png' %}" alt="">
            </a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="om-widget">
            <ul>
                <li><i class="icon_mail_alt"></i> Aler.support@gmail.com</li>
                <li><i class="fa fa-mobile-phone"></i> 125-711-811 <span>125-668-886</span></li>
            </ul>
            <a href="#" class="hw-btn">Submit property</a>
        </div>
        <div class="om-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-youtube-play"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
            <a href="#"><i class="fa fa-pinterest-p"></i></a>
        </div>
    </div>
    <!-- Offcanvas Menu Wrapper End -->



    <!-- Contact Section Begin -->
    {% endblock %}

    {% block jsblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.richtext.min.js' %}"></script>
    <script src="{% static 'js/image-uploader.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% endblock %}

templates/homepage/footer.html
{% load static %}
<!-- Contact Section Begin -->
    <section class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="contact-info">
                        <div class="ci-item">
                            <div class="ci-icon">
                                <i class="fa fa-map-marker"></i>
                            </div>
                            <div class="ci-text">
                                <h5>Địa Chỉ</h5>
                                <p>KTX Khu A ĐHQG TP.HCM, Khu Phố 6, Đông Hòa, Thủ Đức, Bình Dương</p>
                            </div>
                        </div>
                        <div class="ci-item">
                            <div class="ci-icon">
                                <i class="fa fa-mobile"></i>
                            </div>
                            <div class="ci-text">
                                <h5>Điện Thoại</h5>
                                <ul>
                                    <li>96-69-69</li>
                                    <li>125-668-886</li>
                                </ul>
                            </div>
                        </div>
                        <div class="ci-item">
                            <div class="ci-icon">
                                <i class="fa fa-headphones"></i>
                            </div>
                            <div class="ci-text">
                                <h5>Hỗ trợ</h5>
                                <p>Support.abc@gmail.com</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cs-map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.128289908638!2d106.80503545059757!3d10.877845792214735!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174d8a5f4e477e9%3A0x29d5aeb365cee20b!2sKTX%20Khu%20A%20%C4%90HQG%20TP.HCM!5e0!3m2!1svi!2s!4v1586308628738!5m2!1svi!2s" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </div>
    </section>
    <!-- Contact Section End -->

<footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="fs-about">
                        <div class="fs-logo">
                            <a href="#">
                                <img src="{% static 'img/f-logo.png' %}" alt="">
                            </a>
                        </div>
                        <p>Đứng đầu các từ khóa liên quan đến phòng trọ cho thuê, nhà cho thuê, tìm người ở ghép, 70.000+ tin bài trên hệ thống, và tiếp tục tăng
                            , 300.000+ khách truy cập và hơn 2 triệu lượt xem mỗi tháng</p>
                        <div class="fs-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-pinterest-p"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-6">
                    <div class="fs-widget">
                        <h5>Help</h5>
                        <ul>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Contact Support</a></li>
                            <li><a href="#">Knowledgebase</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">FAQs</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-6">
                    <div class="fs-widget">
                        <h5>Links</h5>
                        <ul>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Create Property</a></li>
                            <li><a href="#">My Properties</a></li>
                            <li><a href="{% url 'NguoiDung:register' %}">Register</a></li>
                            <li><a href="{% url 'NguoiDung:login' %}">Login</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="fs-widget">
                        <h5>Newsletter</h5>
                        <p>Deserunt mollit anim id est laborum.</p>
                        <form action="#" class="subscribe-form">
                            <input type="text" placeholder="Email">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="copyright-text">
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://dungtran.top/" target="_blank">dungtran.top</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
        </div>
    </footer>

templates/homepage/navbar.html
{% load static %}
<header class="header-section">
        <div class="hs-top" >
            <div class="container">
                <div class="row">
                    <div class="">
                        <div class="logo">
                            <a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>
                        </div>
                    </div>
                    <div class="col-lg-10">
                        <div class="ht-widget">
                            <ul>
                                <li><i class="icon_mail_alt"></i> nhatro69@gmail.com</li>
                                <li><i class="fa fa-mobile-phone"></i> 125-711-811 <span>125-668-886</span></li>
                            </ul>
                            <a href="{% url 'PhongTro:add' %}" class="hw-btn">Đăng tim mới</a>
                            {% if not user.is_authenticated %}
                                <a href="{% url 'NguoiDung:login' %}" class="hw-btn">Đăng nhập</a>
                                <a href="{% url 'NguoiDung:register' %}" class="hw-btn">Đăng ký</a>
                            {% else %}
<<<<<<< HEAD
                            <a href="{% url 'NguoiDung:profile' user.id %}"><img src="{% static 'img/icons8-user-30.png' %}" alt="" style="position: relative; left: 30px"></a>
=======
                            <a href="{% url 'NguoiDung:profile'  %}"><img src="{% static 'img/icons8-user-30.png' %}" alt="" style="position: relative; left: 30px"></a>
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="canvas-open">
                    <span class="icon_menu"></span>
                </div>
            </div>
        </div>
        <div class="hs-nav">
            <div class="container"">
                <div class="row">
                    <div class="col-lg-9">
                        <nav class="nav-menu">
                            <ul>
                                <li class="active"><a href="{% url 'core:index'%}">Trang chủ</a></li>
                                <li><a href="#">Danh mục</a>
                                    <ul class="dropdown">
                                        <li><a href="./property.html">Cho thuê nhà trọ</a></li>
                                        <li><a href="./profile.html">Nhà cho thuê</a></li>
                                        <li><a href="./property-details.html">Tìm người ở ghép</a></li>
                                        <li><a href="./property-comparison.html">Cho thuê mặt bằng</a></li>
                                        <li><a href="./property-submit.html">Cho thuê căn hộ</a></li>
                                    </ul>
                                </li>
                                <li><a href="./agents.html">Bảng giá dịch vụ</a></li>
                                <li><a href="{% url 'core:about'%}">Thông tin</a></li>
                                <li><a href="{% url 'core:huongdan'%}">Hướng dẫn</a></li>
                                <li><a href="{% url 'core:contact'%}">Liên hệ</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-3">
                        <div class="hn-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-pinterest-p"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>