NguoiDung/urls.py
from django.urls import path
from . import views

app_name = 'NguoiDung'
urlpatterns = [
    path('login/', views.LoginClass.as_view(), name='login'),
    path('register/', views.RegisterClass.as_view(), name='register'),
<<<<<<< HEAD
    path('profile/<id>', views.detail_view, name='profile'),
    path('update/<id>', views.update_view, name='update'),
=======
    path('profile/', views.ProfileClass.as_view(), name='profile'),
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729
]

PhongTro/urls.py
from django.urls import path
from . import views

app_name = 'PhongTro'
urlpatterns = [
    path('', views.index, name='index'),
<<<<<<< HEAD
    path('add', views.post, name='add'),
    path('gets/', views.getAll.as_view(), name='getall'),
    path('detail/<int:PhongTro_id>', views.getdetail.as_view(), name='detail'),
    path('edit/<int:pk>', views.PhongTroUpdate.as_view(), name='phongtro_edit'),
    path('delete/<int:pk>', views.PhongTroDelete.as_view(), name='phongtro_delete'),
=======
    path('add/', views.save_news_class.as_view(), name='add'),
    path('gets/', views.getAll.as_view(), name='getall'),
    path('detail/<int:PhongTro_id>', views.getdetail.as_view(), name='detail'),
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

    path('ajax/load-huyen/', views.load_huyen, name='ajax_load_districts'),
    path('ajax/load-xa/', views.load_xa, name='ajax_load_wards'),
    path('ajax/load-duong/', views.load_duong, name='ajax_load_streets')
]

TimPhongTro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PhongTro/', include("PhongTro.urls")),
    path('NguoiDung/',include("NguoiDung.urls")),
    path('', include("core.urls"))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.Home.as_view(), name='index'),
    path('/about', views.About.as_view(), name='about'),
    path('/contact', views.Contact.as_view(), name='contact'),
    path('/huongdan', views.HuongDan.as_view(), name='huongdan')
]

PhongTro/models.py
from django.db import models
from django.utils import timezone

from DichVu.models import DichVu
from NguoiDung.models import NguoiDung
from DiaChi.models import province
from DiaChi.models import district
from DiaChi.models import ward
from DiaChi.models import street


class PhongTro(models.Model):
<<<<<<< HEAD
    NguoiDung = models.ForeignKey(NguoiDung, on_delete=models.CASCADE, related_name='PhongTro')
=======
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729
    DichVu = models.ForeignKey(DichVu, on_delete=models.CASCADE)
    province = models.ForeignKey(province, on_delete=models.CASCADE)
    district = models.ForeignKey(district, on_delete=models.CASCADE)
    ward = models.ForeignKey(ward, on_delete=models.CASCADE)
    street = models.ForeignKey(street, on_delete=models.CASCADE)
<<<<<<< HEAD
    address = models.CharField(blank=True, max_length=255)  # Địa chỉ
    TieuDe = models.CharField(max_length=100)
    Anh = models.ImageField(upload_to='upload_renting_pic', blank=True)
    Gia = models.DecimalField(max_digits=20, decimal_places=3)
    NgayDang = models.DateField(default=timezone.now)
    NgayCapNhat = models.DateField(auto_now=True, db_index=True)
=======
    TieuDe = models.CharField(max_length=100)
    Anh = models.ImageField(upload_to='', default='images.jpg')
    Gia = models.DecimalField(max_digits=20, decimal_places=3)
    NguoiDung = models.ForeignKey(NguoiDung, on_delete=models.CASCADE, related_name='PhongTro')
    NgayDang = models.DateField(default=timezone.now)
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729
    SDT = models.IntegerField(default=0)
    DienTich = models.IntegerField(default=0)
    NoiDung = models.TextField(max_length=1000)

    def __str__(self):
        return self.TieuDe
<<<<<<< HEAD


def get_image_filename(instance, filename):
    id = instance.post.id
    return "post_images/%s" % (id)


class Images(models.Model):
    phongtro = models.ForeignKey(PhongTro, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='upload_renting_pic')
=======
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

PhongTro/forms.py
from django import forms
<<<<<<< HEAD
from django.forms.widgets import Input

from .models import PhongTro, Images
=======
from .models import PhongTro
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

from DichVu.models import DichVu
from TinhTP.models import TinhTP

from HuyenQuan.models import HuyenQuan
from DiaChi.models import province, district, ward, street
from NguoiDung.models import NguoiDung

<<<<<<< HEAD

class PhongTroForm(forms.ModelForm):
    NoiDung = forms.CharField(label="", widget=forms.Textarea(
        attrs={'class': 'form-control texteditor-content', 'placeholder': 'Nhập bình luận của bạn tại đây !!!'}))
    TieuDe = forms.CharField(label="", widget=Input(
        attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'Nhập tiêu đề của bạn tại đây !!!'}))
    # province = forms.ModelChoiceField(label="c", queryset=province.objects.all(),
    #                                   widget=forms.Select(attrs={'class': 'form-control sm-width w-100', 'placeholder': 'Chọn tỉnh !!!'}))
    # district = forms.ModelChoiceField(label="c", queryset=district.objects.none(),
    #                                   widget=forms.Select(attrs={'class': 'form-control sm-width w-100', 'placeholder': 'Chọn tỉnh !!!'}))
    # ward = forms.ModelChoiceField(label="c", queryset=ward.objects.all(),
    #                                   widget=forms.Select(attrs={'class': 'form-control sm-width w-100', 'placeholder': 'Chọn tỉnh !!!'}))
    # street = forms.ModelChoiceField(label="c", queryset=street.objects.all(),
    #                                   widget=forms.Select(attrs={'class': 'form-control sm-width w-100', 'placeholder': 'Chọn tỉnh !!!'}))

    class Meta:
        model = PhongTro
        fields = (
            'DichVu', 'TieuDe', 'province', 'district', 'ward', 'street', 'Gia', 'SDT',
            'NoiDung', 'DienTich', 'Anh')
=======
class PhongTroForm(forms.ModelForm):
    class Meta:
        model = PhongTro
        fields = ('DichVu','TieuDe','province','district','ward','street','Gia','Anh','NguoiDung','NgayDang','SDT','NoiDung','DienTich')

>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self.data)
        self.fields['district'].queryset = district.objects.none()

        if 'province' in self.data:
            try:
<<<<<<< HEAD
                province_id = int(self.data.get('province'))
                self.fields['district'].queryset = district.objects.filter(_province_id=province_id).order_by('_name')
=======
                country_id = int(self.data.get('province'))
                self.fields['district'].queryset = district.objects.filter(_province_id=country_id).order_by('_name')
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['district'].queryset = self.instance.province._district_set.order_by('_name')
<<<<<<< HEAD


class ImageForm(forms.ModelForm):
    # image = forms.ImageField(label='Image')

    class Meta:
        model = Images
        fields = ('image',)
=======
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

PhongTro/views.py
<<<<<<< HEAD
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import UpdateView, DeleteView

from DiaChi.models import district, ward, street
from .forms import PhongTroForm, ImageForm
from .models import PhongTro, Images
=======
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import decorators, authenticate, login
from django.views import View
from .models import PhongTro

from .forms import PhongTroForm
from .filters import PhongTroFilter
from DiaChi.models import district, province, ward, street
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729


def index(request):
    return HttpResponse("Xin chào")

<<<<<<< HEAD
    # Create your views here.


# class save_news_class(LoginRequiredMixin, View):
#     login_url = '/NguoiDung/login/'
#
#     def get(self, request):
#         a = PhongTroForm()
#         return render(request, 'homepage/PhongTro/add.html', {'f': a})
#
#
#     def post(self, request):
#         g = PhongTroForm(request.POST, request.FILES)
#         if g.is_valid():
#             g.save()
#             return HttpResponse(g)
#         else:
#             return HttpResponse("Không lưu được validate")


def post(request):
    ImageFormSet = modelformset_factory(Images,
                                        form=ImageForm, extra=3)
    if request.method == 'POST':
        form = PhongTroForm(request.POST, request.FILES)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Images.objects.none())
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.NguoiDung = request.user
            post.save()
            for form in formset.cleaned_data:
                image = form['image']
                photo = Images(phongtro=post, image=image)
                photo.save()
            messages.success(request, "Posted!")
            return HttpResponseRedirect("/")
        else:
            print(form.errors, formset.errors)
    else:
        form = PhongTroForm()
        formset = ImageFormSet(queryset=Images.objects.none())
    return render(request, 'homepage/PhongTro/add.html',
                  {'postForm': form, 'formset': formset})
    # return render(request, 'homepage/PhongTro/property-submit.html',
    #               {'postForm': form, 'formset': formset})
=======

# Create your views here.
class save_news_class(LoginRequiredMixin, View):
    login_url = '/NguoiDung/login/'

    def get(self, request):
        a = PhongTroForm()
        #return render(request, 'homepage/PhongTro/property-submit.html', {'f': a})
        return render(request, 'homepage/PhongTro/add.html', {'f': a})

    def post(self, request):
        g = PhongTroForm(request.POST, request.FILES)
        if g.is_valid():
            g.save()
            return HttpResponse(g)
        else:
            return HttpResponse("Không lưu được validate")
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729


class getAll(View):
    def get(self, request):
        a = PhongTroForm()
        return render(request, 'homepage/index.html', {'f': a})

    def post(self, request):
        g = PhongTroForm(request.POST, request.FILES)
        if g.is_valid():
            g.save()
            return HttpResponse(g)
        else:
            return HttpResponse("Không lưu được validate")


<<<<<<< HEAD
class PhongTroUpdate(UpdateView):
    model = PhongTro
    fields = (
        'DichVu', 'TieuDe', 'province', 'district', 'ward', 'street', 'Gia', 'SDT',
        'NoiDung', 'DienTich', 'Anh')
    success_url = reverse_lazy('core:index')


class getdetail(View):
    def get(self, request, PhongTro_id):
        p = PhongTro.objects.get(pk=PhongTro_id)
        return render(request, 'homepage/property-details.html', {'p': p})


class PhongTroDelete(DeleteView):
    model = PhongTro
    # success_url = reverse_lazy('NguoiDung:profile')
    success_url = "/NguoiDung/profile/{NguoiDung_id}"
=======
class getdetail(View):
    def get(self, request, PhongTro_id):
        p = PhongTro.objects.get(pk=PhongTro_id)
        return HttpResponse(p)
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729


def load_huyen(request):
    tinhtp_id = request.GET.get('province')
    districts = district.objects.filter(_province_id=tinhtp_id).order_by('_name')
    return render(request, 'homepage/PhongTro/loadhuyen.html', {'districts': districts})


def load_xa(request):
    tinhtp_id = request.GET.get('district')
    wards = ward.objects.filter(_district_id=tinhtp_id).order_by('_name')
    return render(request, 'homepage/PhongTro/loadxa.html', {'wards': wards})


def load_duong(request):
    tinhtp_id = request.GET.get('district')
    print(tinhtp_id)
    streets = street.objects.filter(_district_id=tinhtp_id).order_by('_name')
    return render(request, 'homepage/PhongTro/loadduong.html', {'streets': streets})

templates/homepage/PhongTro/add.html
<<<<<<< HEAD
{% extends 'homepage/base.html' %}
{% load param_replace %}
{% load static %}

{% block cssblock %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/elegant-icons.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/nice-select.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/richtext.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/image-uploader.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/slicknav.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="container">
    <form action="{% url 'PhongTro:add'%}" data-districts-url="{% url 'PhongTro:ajax_load_districts' %}" data-streets-url="{% url 'PhongTro:ajax_load_streets' %}" data-wards-url="{% url 'PhongTro:ajax_load_wards' %}" enctype="multipart/form-data"  id="phongtroForm" method="POST" novalidate>
<!--{% csrf_token %}-->
<!--            {{ f.as_p}}-->
<!--            <h3>My Google Maps Demo</h3>-->
<!--            &lt;!&ndash;The div element for the map &ndash;&gt;-->
<!--            <div id="map"></div>-->
<!--            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBGhfiQMaLdAk4322oW5YdKHs97CHFeXvI&libraries=places&callback=initMap" async defer></script>-->
<!--            <p><input type="submit" value="Thêm"></p>-->

    {% csrf_token %}
    {% for hidden in postForm.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    {{ postForm.as_p }}

    {{ formset.management_form }}
    {{ formset.as_p}}

    <input name="submit" type="submit" value="Submit"/>
</form>
</div>

{% endblock %}

{% block jsblock %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.richtext.min.js' %}"></script>
<script src="{% static 'js/image-uploader.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
        $(document).ready(function(){
                $("#id_province").change(function () {
=======
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TÌM PHÒNG TRỌ</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<!--    load select location-->
    <script>
        $(document).ready(function(){
                $("#id_province").change(function () {
                  alert($(this).val())
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

                  var url = $("#phongtroForm").attr("data-districts-url");
                  var tinhtpId = $(this).val();

                  $.ajax({
                    url: url,
                    data: {
                      'province': tinhtpId
                      },
                    success: function (data) {
                      $("#id_district").html(data);
                    }
                  });
                });

                $("#id_district").change(function () {

                  var url = $("#phongtroForm").attr("data-wards-url");
                  var huyenId = $(this).val();

                  $.ajax({
                    url: url,
                    data: {
                      'district': huyenId
                      },
                    success: function (data) {
                      $("#id_ward").html(data);
                    }
                  });
                });

                 $("#id_district").change(function () {

                  var url = $("#phongtroForm").attr("data-streets-url");
                  var huyenId = $(this).val();

                  $.ajax({
                    url: url,
                    data: {
                      'district': huyenId
                      },
                    success: function (data) {
                      $("#id_street").html(data);
                    }
                  });
                });
        });
<<<<<<< HEAD

</script>

{% endblock %}
=======
    </script>
    <script>
        // This example requires the Places library. Include the libraries=places
        // parameter when you first load the API. For example:
        // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

        var map;
        var service;
        var infowindow;
        var q = 'Hà Nội';

        function initMap() {
          var sydney = new google.maps.LatLng(-33.867, 151.195);

          infowindow = new google.maps.InfoWindow();

          map = new google.maps.Map(
              document.getElementById('map'), {center: sydney, zoom: 4});

          var request = {
            query: 'Gia lai',
            fields: ['name', 'geometry'],
          };

          service = new google.maps.places.PlacesService(map);

          service.findPlaceFromQuery(request, function(results, status) {
            if (status === google.maps.places.PlacesServiceStatus.OK) {
              for (var i = 0; i < results.length; i++) {
                createMarker(results[i]);
              }

              map.setCenter(results[0].geometry.location);
            }
          });
        }

        function createMarker(place) {
          var marker = new google.maps.Marker({
            map: map,
            position: place.geometry.location
          });

          google.maps.event.addListener(marker, 'click', function() {
            infowindow.setContent(place.name);
            infowindow.open(map, this);
          });
        }
    </script>
    <style>
        #map {
          height: 500px;
          weight: 500px;
        }
        /* Optional: Makes the sample page fill the window. */
        html, body {
          height: 100%;
          margin: 0;
          padding: 0;
        }
    </style>
</head>
<body>
    <form id="phongtroForm" action="{% url 'PhongTro:add'%}" method="POST" enctype="multipart/form-data" data-districts-url="{% url 'PhongTro:ajax_load_districts' %}" data-wards-url="{% url 'PhongTro:ajax_load_wards' %}" data-streets-url="{% url 'PhongTro:ajax_load_streets' %}" novalidate>
        {% csrf_token %}
<!--        <p>Mã dịch vụ {{ f.DichVu }}</p>
        <p>Mã tỉnh {{ f.TinhTP}}</p>
        <p>Mã huyện {{ f.HuyenQuan }}</p>
        <p>Tiêu đề {{ f.TieuDe }}</p>
        <p>Giá {{ f.Gia }}</p>
        <p>Địa chỉ {{ f.DiaChi }}</p>
        <p>Ảnh {{ f.Anh }}</p>
        <p>Người đăng {{ f.NguoiDung }}</p>
        <p>Ngày đăng {{ f.NgayDang }}</p>
        <p>Số điện thoại {{ f.SDT }}</p>
        <p>Nội dung {{ f.NoiDung }}</p>
        <p>Diện tích {{ f.DienTich }}</p>-->
        {{ f.as_p}}
        <h3>My Google Maps Demo</h3>
        <!--The div element for the map -->
        <div id="map"></div>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBGhfiQMaLdAk4322oW5YdKHs97CHFeXvI&libraries=places&callback=initMap" async defer></script>
        <p><input type="submit" value="Thêm"></p>
    </form>
</body>
</html>
>>>>>>> 2c68a77a700e53c38815547a749e531e88085729

templates/homepage/PhongTro/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Tìm phòng trọ</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'PhongTro/unnamed.png' %}">
  <style>
  .fakeimg {
    height: 200px;
    background: #aaa;
  }
  </style>
</head>
<body>

<div class="jumbotron text-center" style="margin-bottom:0">
  <img src="{% static 'PhongTro/unnamed.png' %}" alt="My image" style="width:100px;height:100px;">
  <p>Trang web tìm nhà trọ số 1 Việt Nam</p>
</div>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="#">Trang Chủ</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Cho thuê nhà trọ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Nhà cho thuê</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Cho thuê căn hộ</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Cho thuê mặt bằng</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Tìm người ở ghép</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Cho thuê căn hộ</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Hướng dẫn</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Nạp tiền</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Bảng giá dịch vụ</a>
      </li>
      {% if not NguoiDung.is.authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'NguoiDung:login' %}">Đăng nhập</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

<div class="noidung">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/homepage/PhongTro/list.html
{% extends 'PhongTro/base.html' %}

    {% block content %}
        <div>
            {% if list %}
                <h1>Danh sách phòng trọ:</h1>
                {% for item in list %}
                    <div class="container">
                      <div class="row">
                          <div class="">
                              <a href="/PhongTro/detail/{{item.id}}"><h3>{{ item.TieuDe }}</h3></a>
                              <img src="{{ item.Anh.url }}" alt="{{ item.Anh.url }}" style="width:150px;height:100px;">

                          </div>
                      </div>
                    </div>
                {% endfor %}
            {% else %}
                <h1>Không tồn tại Phòng trọ nào</h1>
            {% endif %}
        </div>

    {% endblock %}

templates/homepage/PhongTro/loadhuyen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <option value="">---------</option>
    {% for district in districts %}
    <option value="{{ district.pk }}">{{ district }}</option>
    {% endfor %}

</body>
</html>

templates/homepage/PhongTro/phongtro_form.html
{% extends 'PhongTro/base.html' %}
{% load static %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Đăng">
    </form>
{% endblock %}